testing

In [1]:
from edgar import *
set_identity("dattasohamai@gmail.com")

c:\dev\Projects\agentic_fin_assistant\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
company = Company("AAPL")
filing = company.get_filings(form = ['10-K', '10-Q'])

In [19]:
xbrl = filing.xbrl()

In [22]:
print(xbrl)

╭──────────────────────────────────── 10-Q Apple Inc. (AAPL) • CIK 0000320193 ────────────────────────────────────╮
│   Fiscal Period       Q2 2026 (ended Mar 28, 2026)                                                              │
│   Data                845 facts • 158 contexts                                                                  │
│                                                                                                                 │
│ Periods                                                                                                         │
│   Quarterly           Q1 2026, Q1 2025                                                                          │
│   (1 future period after 2026-03-28 excluded)                                                                   │
│                                                                                                                 │
│ Statements (49)                                                                                                 │
│   Statements        Income, Compr. Income, Balance Sheet, Equity, Cash Flow                                     │
│   Notes             Insider Trading Arrangements, 9952162 - Disclosure - Debt, 9952158 - Disclosure - Revenue,  │
│   Disclosures       Pvp Disclosure, Err Comp Disclosure, Award Timing Disclosure, 9955530 - Disclosure - Debt - │
│   Document          0000001 - Document - Cover Page                                                             │
│   Other             Insider Trading Policies Proc                                                               │
╰───────────────────────────────────────────────────────────────────────── XBRL Data • xbrl.statements to browse ─╯

In [21]:
xbrl.statements

╭─────────────────────────────────────── Statements (49) Apple Inc. (AAPL) ───────────────────────────────────────╮
│     #   Statement                       Accessor                                                                │
│ ───────────────────────────────────────────────────────────────────────────                                     │
│     1   Income Statement                .income_statement()                                                     │
│     2   Comprehensive Income            .comprehensive_income()                                                 │
│     3   Balance Sheet                   .balance_sheet()                                                        │
│     4   Balance Sheet (Parenthetical)   .balance_sheet(parenthetical=True)                                      │
│     5   Equity                          .statement_of_equity()                                                  │
│     6   Cash Flow Statement             .cashflow_statement()                                                   │
│                                                                                                                 │
│  Notes  Insider Trading Arrangements, 9952162 - Disclosure - Debt, 9952158 - Disclosure - Revenue, 9955516 - …  │
│  Disc…  Pvp Disclosure, Err Comp Disclosure, Award Timing Disclosure, 9955530 - Disclosure - Debt - Additiona…  │
│  Docu…  0000001 - Document - Cover Page                                                                         │
│  Other  Insider Trading Policies Proc                                                                           │
╰──────────────────────────────────── .search() • .list_available() • .get() ─────────────────────────────────────╯

In [53]:
revenue = xbrl.statements.comprehensive_income()
print(revenue)

                                                    APPLE INC.   AAPL
                                                    CONSOLIDATED STATEMENT OF COMPREHENSIVE INCOME
                                                    Mar 29, 2025 (YTD) to Mar 28, 2026 (Q2)

                                                                   Mar 28, 2026 (Q2)   Mar 29, 2025 (Q2)   Mar 28, 2026 (YTD)   Mar 29, 2025 (YTD)
   ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        Net income:                                                           29,578              24,780               71,675               61,110
    Other comprehensive income/(loss):
        Change in foreign currency translation, net of tax                        67                  90                 (92)                (535)
      Change in unrealized gains/losses on derivative
    instruments, net of tax:
            Change in fair value of derivative instruments                       162               (318)                  373                1,333
            Adjustment for net (gains)/losses realized and                      (44)                 628                (281)                (156)
    included in net income
            Total change in unrealized gains/losses on                           206               (946)                  654                1,489
    derivative instruments
      Change in unrealized gains/losses on marketable debt
    securities, net of tax:
            Change in fair value of marketable debt securities                 (808)               1,097                (384)                (550)
            Adjustment for net (gains)/losses realized and                      (14)               (185)                 (18)                (405)
    included in net income
            Total change in unrealized gains/losses on                         (794)               1,282                (366)                (145)
    marketable debt securities
        Other comprehensive income/(loss):                                     (521)                 426                  196                  809
      Total comprehensive income                                              29,057              25,206               71,871               61,919

   Source: SEC XBRL

In [51]:
df_clean = revenue.to_dataframe(view = 'detailed').iloc[:,1:10]

In [52]:
print(df_clean.to_markdown())

|    | label                                        | standard_concept               |   2026-03-28 (Q2) |   2025-03-29 (Q2) |   2026-03-28 (YTD) |   2025-03-29 (YTD) |   level | abstract   | dimension   |
|---:|:---------------------------------------------|:-------------------------------|------------------:|------------------:|-------------------:|-------------------:|--------:|:-----------|:------------|
|  0 | Net sales                                    | Revenue                        |       1.11184e+11 |       9.5359e+10  |        2.5494e+11  |        2.19659e+11 |       4 | False      | False       |
|  1 | Products                                     | nan                            |       8.0208e+10  |       6.8714e+10  |        1.93951e+11 |        1.66674e+11 |       4 | False      | True        |
|  2 | iPhone                                       | nan                            |       5.6994e+10  |       4.6841e+10  |        1.42263e+11 |        1.15979e+11 |       4 | False      | True        |
|  3 | Mac                                          | nan                            |       8.399e+09   |       7.949e+09   |        1.6785e+10  |        1.6936e+10  |       4 | False      | True        |
|  4 | iPad                                         | nan                            |       6.914e+09   |       6.402e+09   |        1.5509e+10  |        1.449e+10   |       4 | False      | True        |
|  5 | Wearables, Home and Accessories              | nan                            |       7.901e+09   |       7.522e+09   |        1.9394e+10  |        1.9269e+10  |       4 | False      | True        |
|  6 | Services                                     | nan                            |       3.0976e+10  |       2.6645e+10  |        6.0989e+10  |        5.2985e+10  |       4 | False      | True        |
|  7 | Operating segments - Americas                | nan                            |       4.5093e+10  |       4.0315e+10  |        1.03622e+11 |        9.2963e+10  |       4 | False      | True        |
|  8 | Operating segments - Europe                  | nan                            |       2.8055e+10  |       2.4454e+10  |        6.6201e+10  |        5.8315e+10  |       4 | False      | True        |
|  9 | Operating segments - Greater China           | nan                            |       2.0497e+10  |       1.6002e+10  |        4.6023e+10  |        3.4515e+10  |       4 | False      | True        |
| 10 | Operating segments - Japan                   | nan                            |       8.401e+09   |       7.298e+09   |        1.7814e+10  |        1.6285e+10  |       4 | False      | True        |
| 11 | Operating segments - Rest of Asia Pacific    | nan                            |       9.138e+09   |       7.29e+09    |        2.128e+10   |        1.7581e+10  |       4 | False      | True        |
| 12 | Cost of sales                                | CostOfGoodsAndServicesSold     |       5.6403e+10  |       5.0492e+10  |        1.30928e+11 |        1.16517e+11 |       4 | False      | False       |
| 13 | Products                                     | nan                            |       4.9179e+10  |       4.403e+10   |        1.16657e+11 |        1.03477e+11 |       4 | False      | True        |
| 14 | Services                                     | nan                            |       7.224e+09   |       6.462e+09   |        1.4271e+10  |        1.304e+10   |       4 | False      | True        |
| 15 | Operating segments - Americas                | nan                            |       2.3114e+10  |       2.1094e+10  |        5.4963e+10  |        4.9589e+10  |       4 | False      | True        |
| 16 | Operating segments - Europe                  | nan                            |       1.3756e+10  |       1.3025e+10  |        3.2817e+10  |        3.1068e+10  |       4 | False      | True        |
| 17 | Operating segments - Greater China           | nan                            |       1.0633e+10  |       8.794e+09   |        2.3663e+10  |        1.8553e+10  |       4 | False      | True        |
| 18 | Operating segments - Japan                   | nan                            |       4.267e+09   |       3.61e+09    |        8.778e+09   |        8.003e+09   |       4 | False      | True        |
| 19 | Operating segments - Rest of Asia Pacific    | nan                            |       4.633e+09   |       3.969e+09   |        1.0707e+10  |        9.304e+09   |       4 | False      | True        |
| 20 | Gross margin                                 | GrossProfit                    |       5.4781e+10  |       4.4867e+10  |        1.24012e+11 |        1.03142e+11 |       3 | False      | False       |
| 21 | Operating expenses:                          | nan                            |     nan           |     nan           |      nan           |      nan           |       3 | True       | False       |
| 22 | Research and development                     | ResearchAndDevelopmentExpenses |       1.1419e+10  |       8.55e+09    |        2.2306e+10  |        1.6818e+10  |       5 | False      | False       |
| 23 | Corporate non-segment                        | nan                            |       1.1419e+10  |       8.55e+09    |        2.2306e+10  |        1.6818e+10  |       5 | False      | True        |
| 24 | Selling, general and administrative          | SellingGeneralAndAdminExpenses |       7.477e+09   |       6.728e+09   |        1.4969e+10  |        1.3903e+10  |       5 | False      | False       |
| 25 | Total operating expenses                     | TotalOperatingExpenses         |       1.8896e+10  |       1.5278e+10  |        3.7275e+10  |        3.0721e+10  |       5 | False      | False       |
| 26 | Operating income                             | OperatingIncomeLoss            |       3.5885e+10  |       2.9589e+10  |        8.6737e+10  |        7.2421e+10  |       4 | False      | False       |
| 27 | Operating segments - Americas                | nan                            |       1.9373e+10  |       1.6774e+10  |        4.3326e+10  |        3.8283e+10  |       4 | False      | True        |
| 28 | Operating segments - Europe                  | nan                            |       1.3052e+10  |       1.0316e+10  |        3.0842e+10  |        2.4923e+10  |       4 | False      | True        |
| 29 | Operating segments - Greater China           | nan                            |       9.189e+09   |       6.626e+09   |        2.0981e+10  |        1.4786e+10  |       4 | False      | True        |
| 30 | Operating segments - Japan                   | nan                            |       3.839e+09   |       3.434e+09   |        8.452e+09   |        7.748e+09   |       4 | False      | True        |
| 31 | Operating segments - Rest of Asia Pacific    | nan                            |       4.127e+09   |       2.986e+09   |        9.813e+09   |        7.57e+09    |       4 | False      | True        |
| 32 | Corporate non-segment                        | nan                            |      -1.3695e+10  |      -1.0547e+10  |       -2.6677e+10  |       -2.0889e+10  |       4 | False      | True        |
| 33 | Other income/(expense), net                  | NonoperatingIncomeExpense      |      -5.2e+07     |      -2.79e+08    |        9.8e+07     |       -5.27e+08    |       4 | False      | False       |
| 34 | Income before provision for income taxes     | PretaxIncomeLoss               |       3.5833e+10  |       2.931e+10   |        8.6835e+10  |        7.1894e+10  |       3 | False      | False       |
| 35 | Provision for income taxes                   | IncomeTaxes                    |       6.255e+09   |       4.53e+09    |        1.516e+10   |        1.0784e+10  |       3 | False      | False       |
| 36 | Net income                                   | NetIncome                      |       2.9578e+10  |       2.478e+10   |        7.1675e+10  |        6.111e+10   |       3 | False      | False       |
| 37 | Retained earnings/(Accumulated deficit)      | nan                            |       2.9578e+10  |       2.478e+10   |        7.1675e+10  |        6.111e+10   |       4 | False      | True        |
| 38 | Earnings per share:                          | nan                            |     nan           |     nan           |      nan           |      nan           |       3 | True       | False       |
| 39 | Basic (in dollars per share)                 | nan                            |       2.02        |       1.65        |        4.87        |        4.06        |       4 | False      | False       |
| 40 | Diluted (in dollars per share)               | nan                            |       2.01        |       1.65        |        4.85        |        4.05        |       4 | False      | False       |
| 41 | Shares used in computing earnings per share: | nan                            |     nan           |     nan           |      nan           |      nan           |       3 | True       | False       |
| 42 | Basic (in shares)                            | SharesAverage                  |       1.46733e+10 |       1.49941e+10 |        1.47107e+10 |        1.50379e+10 |       4 | False      | False       |
| 43 | Diluted (in shares)                          | SharesFullyDilutedAverage      |       1.47259e+10 |       1.50561e+10 |        1.47681e+10 |        1.51035e+10 |       4 | False      | False       |

In [7]:
df = revenue.to_dataframe()
df

,concept,label,standard_concept,2025-09-27 (FY),2024-09-28 (FY),2023-09-30 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_RevenueFromContractWithCustomerExcludi...,Net sales,Revenue,4.161610e+11,3.910350e+11,3.832850e+11,4,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
1,us-gaap_RevenueFromContractWithCustomerExcludi...,Products,NaN,3.070030e+11,2.948660e+11,2.980850e+11,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ProductMember,Products,srt:ProductOrServiceAxis: Products,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
2,us-gaap_RevenueFromContractWithCustomerExcludi...,iPhone,NaN,2.095860e+11,2.011830e+11,2.005830e+11,4,False,True,False,srt:ProductOrServiceAxis,aapl_IPhoneMember,iPhone,srt:ProductOrServiceAxis: iPhone,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
3,us-gaap_RevenueFromContractWithCustomerExcludi...,Mac,NaN,3.370800e+10,2.998400e+10,2.935700e+10,4,False,True,False,srt:ProductOrServiceAxis,aapl_MacMember,Mac,srt:ProductOrServiceAxis: Mac,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
4,us-gaap_RevenueFromContractWithCustomerExcludi...,iPad,NaN,2.802300e+10,2.669400e+10,2.830000e+10,4,False,True,False,srt:ProductOrServiceAxis,aapl_IPadMember,iPad,srt:ProductOrServiceAxis: iPad,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
5,us-gaap_RevenueFromContractWithCustomerExcludi...,"Wearables, Home and Accessories",NaN,3.568600e+10,3.700500e+10,3.984500e+10,4,False,True,False,srt:ProductOrServiceAxis,aapl_WearablesHomeandAccessoriesMember,"Wearables, Home and Accessories","srt:ProductOrServiceAxis: Wearables, Home and ...",credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
6,us-gaap_RevenueFromContractWithCustomerExcludi...,Services,NaN,1.091580e+11,9.616900e+10,8.520000e+10,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ServiceMember,Services,srt:ProductOrServiceAxis: Services,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
7,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Americas,NaN,1.783530e+11,1.670450e+11,1.625600e+11,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
8,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Europe,NaN,1.110320e+11,1.013280e+11,9.429400e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
9,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Greater China,NaN,6.437700e+10,6.695200e+10,7.255900e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
10,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Japan,NaN,2.870300e+10,2.505200e+10,2.425700e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
11,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Rest of Asia Pacific,NaN,3.369600e+10,3.065800e+10,2.961500e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
12,us-gaap_RevenueFromContractWithCustomerExcludi...,U.S.,NaN,1.517900e+11,1.421960e+11,1.385730e+11,4,False,True,True,srt:StatementGeographicalAxis,country_US,U.S.,srt:StatementGeographicalAxis: U.S.,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
13,us-gaap_RevenueFromContractWithCustomerExcludi...,China,NaN,6.437700e+10,6.695200e+10,7.255900e+10,4,False,True,True,srt:StatementGeographicalAxis,country_CN,China,srt:StatementGeographicalAxis: China,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
14,us-gaap_RevenueFromContractWithCustomerExcludi...,Other countries,NaN,1.999940e+11,1.818870e+11,1.721530e+11,4,False,True,True,srt:StatementGeographicalAxis,aapl_OtherCountriesMember,Other countries,srt:StatementGeographicalAxis: Other countries,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
15,us-gaap_CostOfGoodsAndServicesSold,Cost of sales,CostOfGoodsAndServicesSold,2.209600e+11,2.103520e+11,2.141370e+11,4,False,False,False,NaN,NaN,NaN,NaN,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
16,us-gaap_CostOfGoodsAndServicesSold,Products,NaN,1.941160e+11,1.852330e+11,1.892820e+11,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ProductMember,Products,srt:ProductOrServiceAxis: Products,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
17,us-gaap_CostOfGoodsAndServicesSold,Services,NaN,2.684400e+10,2.511900e+10,2.485500e+10,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ServiceMember,Services,srt:ProductOrServiceAxis: Services,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
18,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Americas,NaN,9.569900e+10,8.958700e+10,9.239400e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
19,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Europe,NaN,5.861700e+10,5.519700e+10,5.410100e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
20,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Greater China,NaN,3.514100e+10,3.751900e+10,3.978700e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
21,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Japan,NaN,1.377900e+10,1.174400e+10,1.154200e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
22,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Rest of Asia Pacific,NaN,1.772400e+10,1.630500e+10,1.631300e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
23,us-gaap_GrossProfit,Gross margin,GrossProfit,1.952010e+11,1.806830e+11,1.691480e+11,3,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_StatementLineItems
24,us-gaap_OperatingExpensesAbstract,Operating expenses:,NaN,NaN,NaN,NaN,3,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
25,us-gaap_ResearchAndDevelopmentExpense,Research and development,ResearchAndDevelopmentExpenses,3.455000e+10,3.137000e+10,2.991500e+10,5,False,False,False,NaN,NaN,NaN,NaN,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
26,us-gaap_ResearchAndDevelopmentExpense,Corporate non-segment,NaN,3.455000e+10,3.137000e+10,2.991500e+10,5,False,True,True,srt:ConsolidationItemsAxis,us-gaap_CorporateNonSegmentMember,Corporate non-segment,srt:ConsolidationItemsAxis: Corporate non-segment,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
27,us-gaap_SellingGeneralAndAdministrativeExpense,"Selling, general and administrative",SellingGeneralAndAdminExpenses,2.760100e+10,2.609700e+10,2.493200e+10,5,False,False,False,NaN,NaN,NaN,NaN,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
28,us-gaap_OperatingExpenses,Total operating expenses,TotalOperatingExpenses,6.215100e+10,5.746700e+10,5.484700e+10,5,False,False,False,NaN,NaN,NaN,NaN,NaN,-1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_OperatingExpensesAbstract
29,us-gaap_OperatingIncomeLoss,Operating income,OperatingIncomeLoss,1.330500e+11,1.232160e+11,1.143010e+11,4,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
30,us-gaap_OperatingIncomeLoss,Operating segments - Americas,NaN,7.248000e+10,6.765600e+10,6.050800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
31,us-gaap_OperatingIncomeLoss,Operating segments - Europe,NaN,4.773900e+10,4.179000e+10,3.609800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
32,us-gaap_OperatingIncomeLoss,Operating segments - Greater China,NaN,2.691700e+10,2.708200e+10,3.032800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
33,us-gaap_OperatingIncomeLoss,Operating segments - Japan,NaN,1.395500e+10,1.245400e+10,1.188800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
34,us-gaap_OperatingIncomeLoss,Operating segments - Rest of Asia Pacific,NaN,1.458600e+10,1.306200e+10,1.206600e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
35,us-gaap_OperatingIncomeLoss,Corporate non-segment,NaN,-4.262700e+10,-3.882800e+10,-3.658700e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_CorporateNonSegmentMember,Corporate non-segment,srt:ConsolidationItemsAxis: Corporate non-segment,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
36,us-gaap_NonoperatingIncomeExpense,"Other income/(expense), net",NonoperatingIncomeExpense,-3.210000e+08,2.690000e+08,-5.650000e+08,4,False,False,False,NaN,NaN,NaN,NaN,NaN,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
37,us-gaap_IncomeLossFromContinuingOperationsBefo...,Income before provision for income taxes,PretaxIncomeLoss,1.327290e+11,1.234850e+11,1.137360e+11,3,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_NetIncomeLoss,us-gaap_StatementLineItems
38,us-gaap_IncomeTaxExpenseBenefit,Provision for income taxes,IncomeTaxes,2.071900e+10,2.974900e+10,1.674100e+10,3,False,False,False,NaN,NaN,NaN,NaN,debit,-1.0,1.0,us-gaap_NetIncomeLoss,us-gaap_StatementLineItems
39,us-gaap_NetIncomeLoss,Net income,NetIncome,1.120100e+11,9.373600e+10,9.699500e+10,3,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,NaN,us-gaap_StatementLineItems
40,us-gaap_NetIncomeLoss,Retained earnings/(Accumulated deficit),NaN,1.120100e+11,9.373600e+10,9.699500e+10,4,False,True,True,us-gaap:StatementEquityComponentsAxis,us-gaap_RetainedEarningsMember,Retained earnings/(Accumulated deficit),us-gaap:StatementEquityComponentsAxis: Retaine...,credit,1.0,1.0,NaN,us-gaap_StatementLineItems
41,us-gaap_EarningsPerShareAbstract,Earnings per share:,NaN,NaN,NaN,NaN,3,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
42,us-gaap_EarningsPerShareBasic,Basic (in dollars per share),NaN,7.490000e+00,6.110000e+00,6.160000e+00,4,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,us-gaap_EarningsPerShareAbstract
43,us-gaap_EarningsPerShareDiluted,Diluted (in dollars per share),NaN,7.460000e+00,6.080000e+00,6.130000e+00,4,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,us-gaap_EarningsPerShareAbstract
44,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Shares used in computing earnings per share:,NaN,NaN,NaN,NaN,3,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
45,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Basic (in shares),SharesAverage,1.494850e+10,1.534378e+10,1.574423e+10,4,False,False,False,NaN,NaN,NaN,NaN,NaN,1.0,1.0,us-gaap_WeightedAverageNumberOfDilutedSharesOu...,us-gaap_WeightedAverageNumberOfSharesOutstandi...
46,us-gaap_WeightedAverageNumberOfDilutedSharesOu...,Diluted (in shares),SharesFullyDilutedAverage,1.500470e+10,1.540810e+10,1.581255e+10,4,False,False,False,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,us-gaap_WeightedAverageNumberOfSharesOutstandi...

In [8]:
mkdwn = df.to_markdown()

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame(df)

In [17]:
df

,concept,label,standard_concept,2025-09-27 (FY),2024-09-28 (FY),2023-09-30 (FY),level,abstract,dimension,is_breakdown,dimension_axis,dimension_member,dimension_member_label,dimension_label,balance,weight,preferred_sign,parent_concept,parent_abstract_concept
0,us-gaap_RevenueFromContractWithCustomerExcludi...,Net sales,Revenue,4.161610e+11,3.910350e+11,3.832850e+11,4,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
1,us-gaap_RevenueFromContractWithCustomerExcludi...,Products,NaN,3.070030e+11,2.948660e+11,2.980850e+11,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ProductMember,Products,srt:ProductOrServiceAxis: Products,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
2,us-gaap_RevenueFromContractWithCustomerExcludi...,iPhone,NaN,2.095860e+11,2.011830e+11,2.005830e+11,4,False,True,False,srt:ProductOrServiceAxis,aapl_IPhoneMember,iPhone,srt:ProductOrServiceAxis: iPhone,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
3,us-gaap_RevenueFromContractWithCustomerExcludi...,Mac,NaN,3.370800e+10,2.998400e+10,2.935700e+10,4,False,True,False,srt:ProductOrServiceAxis,aapl_MacMember,Mac,srt:ProductOrServiceAxis: Mac,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
4,us-gaap_RevenueFromContractWithCustomerExcludi...,iPad,NaN,2.802300e+10,2.669400e+10,2.830000e+10,4,False,True,False,srt:ProductOrServiceAxis,aapl_IPadMember,iPad,srt:ProductOrServiceAxis: iPad,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
5,us-gaap_RevenueFromContractWithCustomerExcludi...,"Wearables, Home and Accessories",NaN,3.568600e+10,3.700500e+10,3.984500e+10,4,False,True,False,srt:ProductOrServiceAxis,aapl_WearablesHomeandAccessoriesMember,"Wearables, Home and Accessories","srt:ProductOrServiceAxis: Wearables, Home and ...",credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
6,us-gaap_RevenueFromContractWithCustomerExcludi...,Services,NaN,1.091580e+11,9.616900e+10,8.520000e+10,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ServiceMember,Services,srt:ProductOrServiceAxis: Services,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
7,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Americas,NaN,1.783530e+11,1.670450e+11,1.625600e+11,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
8,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Europe,NaN,1.110320e+11,1.013280e+11,9.429400e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
9,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Greater China,NaN,6.437700e+10,6.695200e+10,7.255900e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
10,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Japan,NaN,2.870300e+10,2.505200e+10,2.425700e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
11,us-gaap_RevenueFromContractWithCustomerExcludi...,Operating segments - Rest of Asia Pacific,NaN,3.369600e+10,3.065800e+10,2.961500e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
12,us-gaap_RevenueFromContractWithCustomerExcludi...,U.S.,NaN,1.517900e+11,1.421960e+11,1.385730e+11,4,False,True,True,srt:StatementGeographicalAxis,country_US,U.S.,srt:StatementGeographicalAxis: U.S.,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
13,us-gaap_RevenueFromContractWithCustomerExcludi...,China,NaN,6.437700e+10,6.695200e+10,7.255900e+10,4,False,True,True,srt:StatementGeographicalAxis,country_CN,China,srt:StatementGeographicalAxis: China,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
14,us-gaap_RevenueFromContractWithCustomerExcludi...,Other countries,NaN,1.999940e+11,1.818870e+11,1.721530e+11,4,False,True,True,srt:StatementGeographicalAxis,aapl_OtherCountriesMember,Other countries,srt:StatementGeographicalAxis: Other countries,credit,1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
15,us-gaap_CostOfGoodsAndServicesSold,Cost of sales,CostOfGoodsAndServicesSold,2.209600e+11,2.103520e+11,2.141370e+11,4,False,False,False,NaN,NaN,NaN,NaN,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
16,us-gaap_CostOfGoodsAndServicesSold,Products,NaN,1.941160e+11,1.852330e+11,1.892820e+11,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ProductMember,Products,srt:ProductOrServiceAxis: Products,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
17,us-gaap_CostOfGoodsAndServicesSold,Services,NaN,2.684400e+10,2.511900e+10,2.485500e+10,4,False,True,False,srt:ProductOrServiceAxis,us-gaap_ServiceMember,Services,srt:ProductOrServiceAxis: Services,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
18,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Americas,NaN,9.569900e+10,8.958700e+10,9.239400e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
19,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Europe,NaN,5.861700e+10,5.519700e+10,5.410100e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
20,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Greater China,NaN,3.514100e+10,3.751900e+10,3.978700e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
21,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Japan,NaN,1.377900e+10,1.174400e+10,1.154200e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
22,us-gaap_CostOfGoodsAndServicesSold,Operating segments - Rest of Asia Pacific,NaN,1.772400e+10,1.630500e+10,1.631300e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,debit,-1.0,1.0,us-gaap_GrossProfit,us-gaap_StatementLineItems
23,us-gaap_GrossProfit,Gross margin,GrossProfit,1.952010e+11,1.806830e+11,1.691480e+11,3,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_StatementLineItems
24,us-gaap_OperatingExpensesAbstract,Operating expenses:,NaN,NaN,NaN,NaN,3,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
25,us-gaap_ResearchAndDevelopmentExpense,Research and development,ResearchAndDevelopmentExpenses,3.455000e+10,3.137000e+10,2.991500e+10,5,False,False,False,NaN,NaN,NaN,NaN,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
26,us-gaap_ResearchAndDevelopmentExpense,Corporate non-segment,NaN,3.455000e+10,3.137000e+10,2.991500e+10,5,False,True,True,srt:ConsolidationItemsAxis,us-gaap_CorporateNonSegmentMember,Corporate non-segment,srt:ConsolidationItemsAxis: Corporate non-segment,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
27,us-gaap_SellingGeneralAndAdministrativeExpense,"Selling, general and administrative",SellingGeneralAndAdminExpenses,2.760100e+10,2.609700e+10,2.493200e+10,5,False,False,False,NaN,NaN,NaN,NaN,debit,1.0,1.0,us-gaap_OperatingExpenses,us-gaap_OperatingExpensesAbstract
28,us-gaap_OperatingExpenses,Total operating expenses,TotalOperatingExpenses,6.215100e+10,5.746700e+10,5.484700e+10,5,False,False,False,NaN,NaN,NaN,NaN,NaN,-1.0,1.0,us-gaap_OperatingIncomeLoss,us-gaap_OperatingExpensesAbstract
29,us-gaap_OperatingIncomeLoss,Operating income,OperatingIncomeLoss,1.330500e+11,1.232160e+11,1.143010e+11,4,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
30,us-gaap_OperatingIncomeLoss,Operating segments - Americas,NaN,7.248000e+10,6.765600e+10,6.050800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
31,us-gaap_OperatingIncomeLoss,Operating segments - Europe,NaN,4.773900e+10,4.179000e+10,3.609800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
32,us-gaap_OperatingIncomeLoss,Operating segments - Greater China,NaN,2.691700e+10,2.708200e+10,3.032800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
33,us-gaap_OperatingIncomeLoss,Operating segments - Japan,NaN,1.395500e+10,1.245400e+10,1.188800e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
34,us-gaap_OperatingIncomeLoss,Operating segments - Rest of Asia Pacific,NaN,1.458600e+10,1.306200e+10,1.206600e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_OperatingSegmentsMember,Operating segments,srt:ConsolidationItemsAxis: Operating segments...,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
35,us-gaap_OperatingIncomeLoss,Corporate non-segment,NaN,-4.262700e+10,-3.882800e+10,-3.658700e+10,4,False,True,True,srt:ConsolidationItemsAxis,us-gaap_CorporateNonSegmentMember,Corporate non-segment,srt:ConsolidationItemsAxis: Corporate non-segment,credit,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
36,us-gaap_NonoperatingIncomeExpense,"Other income/(expense), net",NonoperatingIncomeExpense,-3.210000e+08,2.690000e+08,-5.650000e+08,4,False,False,False,NaN,NaN,NaN,NaN,NaN,1.0,1.0,us-gaap_IncomeLossFromContinuingOperationsBefo...,us-gaap_StatementLineItems
37,us-gaap_IncomeLossFromContinuingOperationsBefo...,Income before provision for income taxes,PretaxIncomeLoss,1.327290e+11,1.234850e+11,1.137360e+11,3,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,us-gaap_NetIncomeLoss,us-gaap_StatementLineItems
38,us-gaap_IncomeTaxExpenseBenefit,Provision for income taxes,IncomeTaxes,2.071900e+10,2.974900e+10,1.674100e+10,3,False,False,False,NaN,NaN,NaN,NaN,debit,-1.0,1.0,us-gaap_NetIncomeLoss,us-gaap_StatementLineItems
39,us-gaap_NetIncomeLoss,Net income,NetIncome,1.120100e+11,9.373600e+10,9.699500e+10,3,False,False,False,NaN,NaN,NaN,NaN,credit,1.0,1.0,NaN,us-gaap_StatementLineItems
40,us-gaap_NetIncomeLoss,Retained earnings/(Accumulated deficit),NaN,1.120100e+11,9.373600e+10,9.699500e+10,4,False,True,True,us-gaap:StatementEquityComponentsAxis,us-gaap_RetainedEarningsMember,Retained earnings/(Accumulated deficit),us-gaap:StatementEquityComponentsAxis: Retaine...,credit,1.0,1.0,NaN,us-gaap_StatementLineItems
41,us-gaap_EarningsPerShareAbstract,Earnings per share:,NaN,NaN,NaN,NaN,3,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
42,us-gaap_EarningsPerShareBasic,Basic (in dollars per share),NaN,7.490000e+00,6.110000e+00,6.160000e+00,4,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,us-gaap_EarningsPerShareAbstract
43,us-gaap_EarningsPerShareDiluted,Diluted (in dollars per share),NaN,7.460000e+00,6.080000e+00,6.130000e+00,4,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,us-gaap_EarningsPerShareAbstract
44,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Shares used in computing earnings per share:,NaN,NaN,NaN,NaN,3,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us-gaap_StatementLineItems
45,us-gaap_WeightedAverageNumberOfSharesOutstandi...,Basic (in shares),SharesAverage,1.494850e+10,1.534378e+10,1.574423e+10,4,False,False,False,NaN,NaN,NaN,NaN,NaN,1.0,1.0,us-gaap_WeightedAverageNumberOfDilutedSharesOu...,us-gaap_WeightedAverageNumberOfSharesOutstandi...
46,us-gaap_WeightedAverageNumberOfDilutedSharesOu...,Diluted (in shares),SharesFullyDilutedAverage,1.500470e+10,1.540810e+10,1.581255e+10,4,False,False,False,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,us-gaap_WeightedAverageNumberOfSharesOutstandi...